### PR TITLE
Identification process

### PR DESCRIPTION
**Pull request by Kev1CO**
This change is [Reviewable](https://reviewable.io/reviews/Kev1CO/optistim/20)

### CODE REVIEW

**Comment by Kev1CO** [comment]
addressing issue #17

**Comment by Kev1CO** [comment]
> addressing issue #17

addressing issue #22 and issue #8

**Comment by Kev1CO** [comment]
*[`data_process/c3d_process.py` line 1 at r5](https://reviewable.io/reviews/Kev1CO/optistim/20#-NjsfMD05Fe5SrKAkTtD:-NjsfMD05Fe5SrKAkTtE:bhna5d) ([raw file](https://github.com/Kev1CO/optistim/blob/0509df117ac1df838f4b0e7091c6569863809583/data_process/c3d_process.py#L1)):*
> ```Python
> import numpy as np
> ```

Should this data process file be in the package ?

**Review by Ipuch — COMMENTED** [review]
> Reviewed 1 of 11 files at r1, 2 of 6 files at r2, 34 of 40 files at r3, 1 of 2 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Kev1CO/optistim/20)* status: all files reviewed, 23 unresolved discussions (waiting on @Kev1CO)

___
*[`data_process/c3d_process.py` line 12 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1feyw3lDty_36-qe0:-Nk1feyw3lDty_36-qe1:b46ivof) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/data_process/c3d_process.py#L12)):*
> ```Python
> 
> 
> class C3dToForce:
> ```

ExtractAnalogForceFromC3D
___
*[`data_process/c3d_process.py` line 27 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1ftuI7TawZSZpIiBV:-Nk1ftuI7TawZSZpIiBW:bbndhe0) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/data_process/c3d_process.py#L27)):*
> ```Python
>         calibration_matrix_path: str = None,
>         for_identification: bool = False,
>         saving_pickle_path: str | list[str] = None,
> ```

method  
.save()
___
*[`data_process/c3d_process.py` line 380 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1gRCKDQ229FiFUFtj:-Nk1gRCKDQ229FiFUFtk:bcofagk) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/data_process/c3d_process.py#L380)):*
> ```Python
>     def __init__(
>         self,
>         pickle_path: str | list[str] = None,
> ```

ForceSensorToMuscleForce
This class maybe still be a helper of an example for now.
___
*[`data_process/c3d_process.py` line 678 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1fTOp5t0oGE9fweH9:-Nk1fTOp5t0oGE9fweHA:bwp031d) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/data_process/c3d_process.py#L678)):*
> ```Python
>     # # input_channel=[6, 0, 1, 2, 3, 4, 5])
> 
>     ForceSensorToMuscleForce(
> ```

object = ForceSensorToMuscleForce()
object.plot()
___
*[`examples/model_integration.py` line 14 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1iRl99Uk1eLJ3Vq4Z:-Nk1iRl99Uk1eLJ3Vq4_:b-fx86yp) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/examples/model_integration.py#L14)):*
> ```Python
> # This problem was build to be integrated and has no objectives nor parameter to optimize.
> # Therefore, the flag for_optimal_control is set to False.
> problem = FunctionalElectricStimulationOptimalControlProgram(
> ```

FunctionalElectricStimulationInitialValueProblem()



_Code quote:_
```Python
FunctionalElectricStimulation
```
___
*[`examples/model_integration.py` line 20 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1igI00t03CtI4VOB0:-Nk1igI00t03CtI4VOB1:b-rx6gmf) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/examples/model_integration.py#L20)):*
> ```Python
>     final_time=1,
>     use_sx=True,
>     for_optimal_control=False,
> ```

delete this entry

ivp = FunctionalElectricStimulationInitialValueProblem()
result = ivp.integrate()
___
*[`examples/pulse_intensity_optimization.py` line 15 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1jM2o257SFyqD3BvS:-Nk1jM2o257SFyqD3BvT:b-gonymy) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/examples/pulse_intensity_optimization.py#L15)):*
> ```Python
> minimum_pulse_intensity = (
>     np.arctanh(-DingModelIntensityFrequency().cr) / DingModelIntensityFrequency().bs
> ) + DingModelIntensityFrequency().Is
> ```

method of DingIntensity
___
*[`examples/pulse_mode_example.py` line 42 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1jadXEEDLHmvqBRH7:-Nk1jadXEEDLHmvqBRH8:bdrifkl) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/examples/pulse_mode_example.py#L42)):*
> ```Python
>     pulse_mode="Triplet",
>     use_sx=True,
>     for_optimal_control=False,
> ```

Remove this entry consider IVP
___
*[`examples/summation_truncation_example.py` line 51 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1jkTY1cpehpg80M4L:-Nk1jkTY1cpehpg80M4M:b-n2ova8) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/examples/summation_truncation_example.py#L51)):*
> ```Python
> plt.show()
> 
> # Example n°2 : This part shows how the truncation_single.pkl, truncation_doublet.pkl and
> ```

In Separate file, sensitivity study i believe.
___
*[`examples/summation_truncation_graph.py` line 1 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1kUHd-7Tv6X42seHz:-Nk1kUHd-7Tv6X42seI-:b-764mx4) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/examples/summation_truncation_graph.py#L1)):*
> ```Python
> import pickle
> ```

In a separate folder, "truncation sensitivity study" ?
___
*[`optistim/custom_objectives.py` line 65 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1l1KD3hJ-SpeuHIDH:-Nk1l1KD3hJ-SpeuHIDI:b-xywaxr) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/custom_objectives.py#L65)):*
> ```Python
>         The difference between the two keys
>         """
>         if minimization_type == "LS":
> ```

leastsquare
___
*[`optistim/custom_objectives.py` line 67 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1l2fxBF364KmJ9yJn:-Nk1l2fxBF364KmJ9yJo:bvxrg20) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/custom_objectives.py#L67)):*
> ```Python
>         if minimization_type == "LS":
>             return force - controller.states[key].cx
>         elif minimization_type == "BF":
> ```

bestfit
___
*[`optistim/identification/parameter_identification.py` line 14 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1lAgACxEqVadMzzRN:-Nk1lAgACxEqVadMzzRO:bdcs65n) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/identification/parameter_identification.py#L14)):*
> ```Python
> 
> 
> class DingModelFrequencyParameterIdentification:
> ```

Why it doesn't inherit from optimalcontrolprogram / FESOCP?

solution  = FESIdentification(model=model,ns=,track_force=,parameters=["A","Km","tau1","tau2"])
___
*[`optistim/identification/parameter_identification.py` line 48 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1mDYKA70yHuZr3NVt:-Nk1mDYKA70yHuZr3NVu:b20n3vw) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/identification/parameter_identification.py#L48)):*
> ```Python
>             The nature of the casadi variables. MX are used if False.
>         n_threads: int
>             The number of thread to use while solving (multi-threading if > 1)
> ```

It's wrong don't list the kwarg, it means it need to be an entry.

Please extract the segmentation of data in a separate class/script/folder.



_Code quote:_
```Python
        objective: list[Objective]
            Additional objective for the system
        ode_solver: OdeSolver
            The ode solver to use
        use_sx: bool
            The nature of the casadi variables. MX are used if False.
        n_threads: int
            The number of thread to use while solving (multi-threading if > 1)
```
___
*[`optistim/integration/intial_guess_from_ocp.py` line 5 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1o73_AAsoFZcJkc-P:-Nk1o73_AAsoFZcJkc-Q:b-waflv8) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/integration/intial_guess_from_ocp.py#L5)):*
> ```Python
> 
> 
> def build_initial_guess_from_ocp(ocp):
> ```

docstrings like you explain to Pierre a friday.
___
*[`optistim/model/ding2003.py` line 26 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1oFl_8JGeIYj_ZoUQ:-Nk1oFl_8JGeIYj_ZoUR:bzbpyf4) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/model/ding2003.py#L26)):*
> ```Python
> 
>     This is the Ding 2003 model using the stimulation frequency in input.
>     """
> ```

Source
___
*[`optistim/model/ding2003.py` line 260 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1oxK14urLtGA5wUVC:-Nk1oxK14urLtGA5wUVD:b420b8k) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/model/ding2003.py#L260)):*
> ```Python
>             sum_multiplier += ri * exp_time  # Part of Eq n°1
>         else:
>             if self._sum_stim_truncation and len(t_stim_prev) > self._sum_stim_truncation:
> ```

has_more_stim_than_truncation_limit = len(t_stim_prev) > self._sum_stim_truncation
enough_stim_to_truncate = ...



_Code quote:_
```Python
len(t_stim_prev) > self._sum_stim_truncation
```
___
*[`optistim/model/hmed2018.py` line 193 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1pJw70xJ5Jpm8APJQ:-Nk1pJw8B2WShaSa0UvN:b-ojj54d) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/model/hmed2018.py#L193)):*
> ```Python
>         """
>         sum_multiplier = 0
>         if self._sum_stim_truncation and len(extra_arguments["t_stim_prev"]) > self._sum_stim_truncation:
> ```

extra argument should be removed in some way like done before ?



_Code quote:_
```Python
extra_arguments["t_stim_prev"]
```
___
*[`optistim/optimization/fes_identification_ocp.py` line 26 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1q0IpBvJ0Dfk0qtPc:-Nk1q0IpBvJ0Dfk0qtPd:b-2mem9m) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/optimization/fes_identification_ocp.py#L26)):*
> ```Python
> 
> 
> class FunctionalElectricStimulationOptimalControlProgramIdentification(OptimalControlProgram):
> ```

def __init___(...)
     super.init()
     
___
*[`optistim/optimization/fes_identification_ocp.py` line 67 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1pcsfEsDsVR1qDQ3B:-Nk1pcsfEsDsVR1qDQ3C:b-l1x2if) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/optimization/fes_identification_ocp.py#L67)):*
> ```Python
>             The nature of the casadi variables. MX are used if False.
>         n_threads: int
>             The number of thread to use while solving (multi-threading if > 1)
> ```

kwarg bye bye make them real arguments.



_Code quote:_
```Python
        objective: list[Objective]
            Additional objective for the system
        ode_solver: OdeSolver
            The ode solver to use
        use_sx: bool
            The nature of the casadi variables. MX are used if False.
        n_threads: int
            The number of thread to use while solving (multi-threading if > 1)
```
___
*[`optistim/optimization/fes_identification_ocp.py` line 198 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1rHl8AB3bOC4X5BXJ:-Nk1rHl8AB3bOC4X5BXK:bxd13p0) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/optimization/fes_identification_ocp.py#L198)):*
> ```Python
>                 raise ValueError("n_thread kwarg must be a int type")
> 
>         super().__init__(
> ```

fesi = fesidentification(FESOCP)
   def _init__(...)
    super().init
   def prepare_ocp(...)
    return OptimalControlProgram(model=...,
       ...)
ocp = fesi.prepare_ocp()
ocp.solve()
___
*[`optistim/optimization/fes_identification_ocp.py` line 217 at r6](https://reviewable.io/reviews/Kev1CO/optistim/20#-Nk1poeg3Flw1U9TXWP_:-Nk1poeg3Flw1U9TXWPa:b44agt1) ([raw file](https://github.com/Kev1CO/optistim/blob/6596d156321fe11a335388ce5261e2c494be5f9d/optistim/optimization/fes_identification_ocp.py#L217)):*
> ```Python
>             parameter_objectives=self.parameter_objectives,
>             phase_transitions=self.phase_transitions,
>             n_threads=kwargs["n_thread"] if "n_thread" in kwargs else 1,
> ```

n_thread = n_threads



_Code quote:_
```Python
kwargs["n_thread"] if "n_thread" in kwargs else 1,
```

**Pull request merged**
